### PR TITLE
DIY KSL Icons!

### PR DESCRIPTION
**Pull request by jehoshua02**
Starting with thememories-icons as a template, creates ksl-icons repository.

This gets us away from fontastic. That means we have control over relative sizing
and positioning against artboards. It also means, that anyone can add icons to 
the icon font. With fontastic, we could not do that.

The build tasks generate a pretty reference page, and dist files, including font files,
sass, and plain old css, as well as svgs if you need them for some odd reason.

### CODE REVIEW

**Comment by jehoshua02** [comment]
@janiv I need to add a CONTRIBUTING.md.

+ [ ] Add a CONTRIBUTING.md file.

**Comment by jehoshua02** [comment]
@janiv 101 files changed. Might be best to pull and look at it locally.

With this pull request, my primary motivation was to convert it from fontastic to our own build process.

Some things that we might still want to do:

+ __Resize icons.__ Right now the icons are sized to fill artboard. The result is that when icons are sitting next to each other they look too close, and they aren't sized well relative to each other. If now is the right time to do resize the icons, I'm all for it. But it will break backward compatibility in existing code that relies on the current sizing of the icons. But then again, we've already broken backward compatibility.
+ __Rename icons.__ Some of the icons are named to describe the icon. Some are named to describe how we use the icon. I would like the names to describe the icon and setup aliases in ksl-styles to describe how we use them. If now is the right time to rename the icons, I'm happy to do it. This will also break backward compatibility.
+ __Audit icons.__ Jim and Travis wanted to audit the icons. I think there are some icons they don't want to use anymore, want to replace, or want to add. And if I am correct, they don't feel the icon set is a coherent set of icons. Obviously, auditing the icons will also break backwards compatibility.

I want to discuss with the team before spending more time here. But whatever we are going to do, I'd rather get it all done now, breaking backward compatibility in one release, rather than breaking it over and over with multiple releases.

**Comment by janiv** [comment]
Packages.json is missing the gulp-gh-pages dependency.

**Comment by janiv** [comment]
I have concerns with the .icon style doing outline: none. Refer to http://outlinenone.com/.

**Comment by janiv** [comment]
In _variables.scss, you define a bunch of font-sizes. Can we define those variables with a !default.

**Comment by janiv** [comment]
In regards to renaming icons and this breaking backwards compatibility, I think now is the time to rename icons. However, does it need to break backwards compatibility? Can we manually add the old class names to a deprecated.scss file that extends from the new icon class names?

**Comment by janiv** [comment]
Audit Icons can happen in another pull-request. I'd like to get Jim and Travis in Github and modifying the file, doing pull-requests, etc to get that done.

**Comment by janiv** [comment]
Resizing icons and fixing artboards... should this happen when Jim and Travis Audit the Icons and let them pick the relative size and artboard position?

**Comment by janiv** [comment]
Done with review.

**Comment by jehoshua02** [comment]
@janiv 

> In regards to renaming icons and this breaking backwards compatibility, I think now is the time to rename icons. However, does it need to break backwards compatibility? Can we manually add the old class names to a deprecated.scss file that extends from the new icon class names?

I guess I'd prefer a hard switch than to let them linger. I'd like to minimize how much deprecated code we keep around and update things to use new code.

**Comment by jehoshua02** [comment]
@janiv See latest commit. Changes made according to feedback.

**Comment by janiv** [comment]
Looks good.

**Pull request merged**
